### ISSUE TITLE
Cant  screen sharing on some apps like FireFox in Wayland (Ubuntu 21.04)

### ISSUE THREAD

**Issue by edurojasr** [snapcrafters/discord#102]
Hi everyone!

thank you for making this snap, I love using it.

now that Ubuntu 21.04 has decided to use Wayland by default, I can no longer share screen from other applications or the entire desktop. only the same discord window can be shared.

already use `'snap connect discord:system-observe` but you still can't share other screens

:(

**Comment by edurojasr** [comment]
After further investigation I have verified that Discord cannot share the screen of:

- Entire desktop
- Terminal
- Firefox (snap)
- Snap Store (Ubuntu store snap)
- Monitor (system monitor)

but it can share the screen of other other applications like:

- Zoom meetings (snap)
- Thunderbird(snap)
- Apple Music (snap)
- Visual Studio Code (snap)

So then it seems that the screen can be shared but limited to specific applications.

**Comment by KorbsStudio** [comment]
A pipeline needs to be added somehow like with OBS on Flatpak.
If you want, you can still switch back to Xorg from Wayland, by clicking the gear icon on your login screen.

**Comment by edurojasr** [comment]
Thanks @KorbsStudio!

Yeah there's the work around to change the session to Xorg, What seems strange to me is that in some applications it works and in others it doesn't

**Comment by KorbsStudio** [comment]
I use Fedora with GNOME 40 Wayland, OBS (Flatpak) does seem to bug out a bit.
I may switch back to Xorg.

**Comment by edurojasr** [comment]
After reading other forums and the flatpack repo, it's appears that discord can only share screens with apps that run on x11 or xWayland.

[Discord Flatpack](https://github.com/flathub/com.discordapp.Discord/issues/89)
[Reddit Linux](https://www.reddit.com/r/linux4noobs/comments/q6vhac/a_guide_for_discord_screen_sharing_on_wayland/)

This is because as of today January 2022 the oficial discord electron app does not support wayland.

This is not a direct snap problem. Maybe there can be a way to push for discord Waylad support?

**Comment by Fuseteam** [comment]
screen sharing seems to work fine on ubuntu 22.04, wayland on intel graphics

**Comment by edurojasr** [comment]
Hi @Fuseteam 

I see that screen share is better know, I'm able to share Firefox, but cannot share the entire desktop.

**Comment by Fuseteam** [comment]
@edurojasr firefox? are you sure you're using the snap version of discord? as far as i can see i can share my desktop fine

**Comment by edurojasr** [comment]
Yes I'm sure :sweat_smile: 

See here
![Screenshot from 2022-05-30 20-04-29](https://user-images.githubusercontent.com/35645729/171078770-9b744276-5ea6-451d-8583-7c79880bbcaf.png)

Also I did all the manual connections, I think the team can update the store page to include this manual connections.

![Screenshot from 2022-05-30 20-05-08](https://user-images.githubusercontent.com/35645729/171078865-42784c51-665a-4c90-aa8a-49a064805108.png)

I can share some apps, not the entire desktop, btw I'm using default Wayland
