### ISSUE TITLE
Discord claims to be corrupt

### ISSUE THREAD

**Issue by popey** [snapcrafters/discord#11]
An OTA update to Discord pops up this now...

![image](https://user-images.githubusercontent.com/1841272/33151753-51e69b74-cfd1-11e7-97c9-a6749e408772.png)
Which takes users to a windows support page... https://support.discordapp.com/hc/en-us/articles/115004307527

**Comment by simoniz0r** [comment]
Package libatomic1 with your snap.

**Comment by popey** [comment]
Thanks @simoniz0r ! That fixed it.
