### ISSUE TITLE
Please Update to Discord 0.0.15

### ISSUE THREAD

**Issue by rafaelmoczalla** [snapcrafters/discord#110]
There was an update announced and I cannot refresh this snap to newest version.

Thanks in advance.

**Comment by kkliebersbach** [comment]
Can confim that the snap cannot be launched due to version.

**Comment by Fuseteam** [comment]
please refer to #107

**Comment by TopMax** [comment]
The stable channel has been updated!

**Comment by Fuseteam** [comment]
confirmed

**Comment by rafaelmoczalla** [comment]
Cool, thanks a lot!
