### ISSUE TITLE
No new message indicator in the Ubuntu dock with the discord snap

### ISSUE THREAD

**Issue by Feichtmeier** [snapcrafters/discord#125]
Unlike the telegram-desktop snap and the discord debian package the discord snap does not show the green new message indicator in the ubuntu dock

![grafik](https://user-images.githubusercontent.com/15329494/171997341-a8d5a91b-afa1-40ec-a8f3-395f82581fe0.png)

**Comment by kenvandine** [comment]
This will be fixed in the platform snap when this is merged https://github.com/ubuntu/gnome-sdk/pull/33

**Comment by Feichtmeier** [comment]
Thanks for the fix!
This has not changed for me since you merged the PR. Does my system eventually miss this gnome sdk snap you merged?
I am using 22.04
Those are the gnome sdk snaps I have installed
![grafik](https://user-images.githubusercontent.com/15329494/186594696-d0685fa6-d433-4f10-9ca7-e2a3a4a9168f.png)

**Comment by kenvandine** [comment]
@Feichtmeier what revision of gnome-3-38-2004 do you have installed?  It's working for me with the version in stable.  And while you're at it, what revision of discord do you have?

**Comment by Feichtmeier** [comment]
@kenvandine I am using the discord snap from latest/stable with version 0.0.19 updated on 16. August
I am using gnome-3-38-2004 from latest/candidate version 0+git.891e5bc updated on june 23

**Comment by kenvandine** [comment]
@Feichtmeier do you get the new message indicator in the panel icon?  Actually I don't get it in the dock either, but I do in the panel icon.

**Comment by Feichtmeier** [comment]
@kenvandine yes the panel works :+1: But not the dock

**Comment by kenvandine** [comment]
The only app i have that displays that in the dock for me is telegram, nothing else does.  Slack, discord, and mattermost all show it in the panel, but none of them in the dock.  Maybe the API electron uses is different than what telegram is using.

**Comment by Feichtmeier** [comment]
Offical debian discord package shows the green message badge though :)

**Comment by Fighter19** [comment]
After I upgrade to Ubuntu 24.04 and reinstalled yesterday, I have this problem again with the snap version.
I'm on Kubuntu however.
