### ISSUE TITLE
Cannot attach files from my steamapps

### ISSUE THREAD

**Issue by fosspill** [snapcrafters/discord#13]
Hello!

It seems like this snap does not have access to my steamapps folder. I often attach screenshots from certain games to Discord. (~/.steam/steam/steamapps/common/Rust/Screenshots f.i.)

**Expected behaviour**
Attach any file that your user owns successfully. Either with drag and drop or the attach file menu.

**Current behaviour**
Attaching files from for instance .steam makes Discord angry and it will not upload the file. Seems to be related to missing access.

**Reasoning for the expected behaviour**
Discord is a voice and chat application made for gamers. Users will share pictures from their games. 

**Current workaround**
Copy picture to ~ before attaching to Discord. 
Remove picture from ~ after sending.

**Comment by Fuseteam** [comment]
this might more be related to how snaps work

**Comment by oleerik** [comment]
Indeed, but even then it's something that should be resolved for Discord to be a smooth, good experience through snaps.

**Comment by Fuseteam** [comment]
this might be a useful read https://askubuntu.com/questions/821823/how-do-snap-applications-snappy-security-r-w-restrictions-and-user-files-work

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting everyone!!

This appears to be fixed now in the latest version of the snap, so I'm closing this issue now. Discord now uses portals, which means you can attach any file. Please comment if this is not the case.
