### ISSUE TITLE
Can't type Japanese characters

### ISSUE THREAD

**Issue by sikthehedgehog** [snapcrafters/discord#15]
Discord seems unable to use the IME (in my case, Anthy) and hence I can't type Japanese characters (copying in/out works just fine, but it's annoying). Japanese characters also appear as boxes, though it seems to be issue #8 (which I'm not entirely sure if it's the fonts or not, I'm only using whatever build was readily available in the snap repo a few days ago).

Also I noticed Discord is not using the native open dialog box which makes me wonder if it's related (it may mean a library issue), though that can also just be a red herring.

Running Ubuntu 16.04 64-bit.

**Comment by SilverEzhik** [comment]
Also seeing the Japanese input issue on Solus 3 (also with Anthy with IBus). I am unable to input text with a Cyrillic keyboard as well.
 
The theme issue is a different problem, from what I know: https://forum.snapcraft.io/t/use-the-system-gtk-theme/496

**Comment by Fuseteam** [comment]
i also seem to have this problem with japanese mozc and pinyin and bopomofo input on ubuntu 16.04
i can input cyrillic just fine however..... i wonder if it has to do with the fact that the three input methods i mention can input multiple script or their usage of a popup to input kanji/hanzi characters

**Comment by Fuseteam** [comment]
i recently fiddled with some enviroment variables and discovered that my japanese and chinese input work with ibus as opposed to xim or vim or uim
maybe its a problem with snaps and ibus?

**Comment by amenoko** [comment]
I'm having this problem as well with ibus+mozc in Ubuntu 17.10.

**Comment by Fuseteam** [comment]
this seems to be a problem with snaps in general as the same problem can be seen in the firefox snap

**Comment by Fuseteam** [comment]
as of this moment in the version 0.05 revision 64 ibus keyboards seem to work

**Comment by Fuseteam** [comment]
in other words i can type japanese characters now

**Comment by Fuseteam** [comment]
this seems solved since the last time i tested

**Comment by Mhankk** [comment]
Have you tried installing Japanese fonts?
https://catalog.monotype.com/language/japanese

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting everyone!!

This appears to be fixed now in the latest version of the snap, so I'm closing this issue now. Please comment if this is not the case.
