### ISSUE TITLE
[Bug]: App doesn't snap to screen requires manual resizing

### ISSUE THREAD

**Issue by neilmartindev** [snapcrafters/discord#159]
### What happened?

The app itself will not snap to half a screen but will take up the fullscreen instead.

### What should have happened?

Snaps to half screen view.

### Output of `snap info discord`

```shell
n/a
```

### Output of `snap connections discord`

```shell
n/a
```

### Output of `snap version`

```shell
n/a
```

**Comment by popey** [comment]
Works fine here on Ubuntu 23.10. Can you perhaps give us a tiny bit more to go on?

[Screencast from 2023-10-12 17-02-27.webm](https://github.com/snapcrafters/discord/assets/1841272/a4340f11-bd37-4db0-a66c-b07c52f5ae40)

**Comment by neilmartindev** [comment]
Sure if I'm doing something daft feel free to let me know :)
[Screencast from 12-10-23 17:08:28.webm](https://github.com/snapcrafters/discord/assets/87085416/ba7be262-2277-4dbe-a265-879df907ff98)

[snapconnection.txt](https://github.com/snapcrafters/discord/files/12884716/snapconnection.txt)
[snapinfodiscord.txt](https://github.com/snapcrafters/discord/files/12884717/snapinfodiscord.txt)
[snapversion.txt](https://github.com/snapcrafters/discord/files/12884718/snapversion.txt)

**Comment by popey** [comment]
I don't know what the algorithm is for when it snaps to the sides or not, sorry. Could you try moving the dock to the bottom temporarily just as a test? I have seen some generic reports of that being a factor. 
Also, does it work if you use Super+Left and Super+Right?

**Comment by neilmartindev** [comment]
Yup, you're bang on. Seems it works on the bottom but struggles with the sides! 
Super L and R is the same, works on the bottom but not on the side.

**Comment by popey** [comment]
Ok, gonna close this, because this is clearly a GNOME/Ubuntu issue, not the discord snap. But thanks for filing it.

**Comment by soupcan97** [comment]
This isn't a bug, the window's minimum width is larger than 50% the viewport width. :)

**Comment by PavanLuca** [comment]
But isn't this a system feature? I have Zorin OS Core 17.1 and dragging the windows to the sides of the screen enlarges the windows to half screen (horizontal or vertical) or full screen depending on which side I touch.
