### ISSUE TITLE
Clicking 'update now' (top-right) creates empty window

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/discord#16]
Similar to #3 , I get an empty Discord window but this time I get this when clicking the 'update now' button in the top right (it looks like the Firefox Download logo, but it's green) and updating via that. I get the new Discord come up but also an unclose-able blank window even if I close the working Discord client. Presumably `snapd` alone should be handling updates, is there an easy way of disabling in-app updates?

**Comment by Fuseteam** [comment]
this doesn't seem to be an issue with discord 0.0.5 revision 71, can you confirm @Ads20000?

**Comment by Ads20000** [comment]
Not sure, I was having audio problems with Discord but I'll try the Discord snap again next time I'm gaming and see if I can reproduce the issue again.
