### ISSUE TITLE
Discord not running at startup

### ISSUE THREAD

**Issue by electricOzone** [snapcrafters/discord#18]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:		16.04
Codename:	xenial

Discord isn't running at startup with "Open Discord" enabled under LINUX SETTINGS -> SYSTEM STARTUP BEHAVIOR.

**Comment by Fuseteam** [comment]
have you tried adding it to the "Start up applications" in ubuntu?
![image](https://user-images.githubusercontent.com/10421851/40089148-8a53ff46-5880-11e8-8391-2b8d44b83af1.png)

**Comment by falconws** [comment]
This is affect for me too.
But this issue appear original discord app too [discord-0.0.5.deb].
This is not snap version issue.

**Comment by kode54** [comment]
I've also had it happen from trying to start it manually from the KDE menu. It starts fine if I launch it running `discord` from a terminal window, I haven't tried the Alt+F2 command box yet.

Running the Snap version on Ubuntu 18.04.1.

**Comment by Pythonic-Rainbow** [comment]
Still not resolved...

**Comment by oshawkat** [comment]
Same problem here.  Running on Ubuntu 16.04.  Discord version 0.0.9.  It has never run at startup for me, even in prior versions.  The Linux Settings > Open Discord option is checked

**Comment by blargle-ragequit** [comment]
Same here with fully updated ArchLinux+KDE with Discord installed from AUR.  I'm adding it to KDE autostart options manually now.

**Comment by Pythonic-Rainbow** [comment]
I left Ubuntu, but is the solution that simple? Just a single `ausostart` line? Can anyone confirm this?

**Comment by kaaloo** [comment]
Not working for me here.  I have the appropriate settings activated:

![image](https://user-images.githubusercontent.com/67010/78760485-8823a180-7981-11ea-88f3-17cfb71f21d8.png)

**Comment by jgrocha** [comment]
You have to wait for a newer update, to get the recent changes already merged.

Meanwhile, you can do:
```bash
cp /var/lib/snapd/desktop/applications/discord_discord.desktop ~/.config/autostart
```

**Comment by I3eef** [comment]
Hi,

short follow up. I ran in this issue as well.
Solved it as @jgrocha described it but also added arguments "--start-minimized" at the end resulting in discord getting started in the background:

`[Desktop Entry]
X-SnapInstanceName=discord
Name=Discord
StartupWMClass=discord
Comment=All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
GenericName=Internet Messenger
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/discord_discord.desktop /var/lib/snapd/snap/bin/discord --start-minimized
Icon=/var/lib/snapd/snap/discord/109/usr/share/discord/discord.png
Type=Application
Categories=Network;InstantMessaging;`

(OS: Fedora)

**Comment by tai271828** [comment]
@jgrocha  and @I3eef 's workaround works for me. Thank you for sharing the tips! My environment: Ubuntu Mate 18.04 and discord version is:

```
$ snap list discord
Name     Version  Rev  Tracking       Publisher     Notes
discord  0.0.13   121  latest/stable  snapcrafters  -
```

**Comment by Fuseteam** [comment]
@tai271828 revision 121 was last updated on the 17th of februari according to `snap info discord`

**Comment by Fuseteam** [comment]
wait this was closed last year :thinking:

**Comment by Fuseteam** [comment]
i suspect this may happen if discord was installed with the feature enabled before the the feature was merged in

**Comment by arn-the-long-beard** [comment]
I am having the issue on Linux Manjaro, but was fine on Linux Mint for some reason.

**Comment by ARehmanMahi** [comment]
Why closed, it still doesn't auto start on ubuntu 20.04

**Comment by kimmymonassar** [comment]
Any progress?

**Comment by SaadBazaz** [comment]
Doesn't work on Zorin OS. I installed Discord from the Software Center.

**Comment by anishkn04** [comment]
> Doesn't work on Zorin OS. I installed Discord from the Software Center.

You can do this:

Search for 'Startup Applications' and open it.
Click on Add option
Type `flatpak run com.discordapp.Discord --start-minimized` in the "Command option"
Type the Name and Comment anything you want and Done!

**Comment by mohssineAboutaj** [comment]
if you are using the **snap** version, follow these steps
1- Open **Terminal** and type
```sh
which discord
```
you will get a path like this `/snap/bin/discord`
2- In the applications search for **Startup Applications** and open it.
3- Click on the **Add** option
4- Paste that path in **Command input** like this
![image](https://github.com/snapcrafters/discord/assets/30943833/06b50627-17e2-4691-8779-4c788f773867)

> Note: the param `--start-minimized` is used to run the app silently when the system is booted

**Comment by bsienn-khan** [comment]
This shit app still doesn't auto start on boot. 
Strange I have 2 laptops, works on one and not the other.
I don't want to go through commands and edits and whatnot. 
Slack got it figured out so well, that I never had issues with them.
