### ISSUE TITLE
Discord not closing properly

### ISSUE THREAD

**Issue by electricOzone** [snapcrafters/discord#19]
Distributor ID: Ubuntu
Description: Ubuntu 16.04.3 LTS
Release: 16.04
Codename: xenial

When clicking "Quit Discord" from the Unity panel in the top right, the Discord window pops up, but doesn't close. Clicking "Quit Discord" repeatedly doesn't work either.

**Comment by popey** [comment]
This appears to now be fixed since snapd 2.31 released.

**Comment by electricOzone** [comment]
Can confirm that the issue is fixed in the new version.
