### ISSUE TITLE
Discord crash at startup. vulkan/icd.d not found

### ISSUE THREAD

**Issue by DheathNone** [snapcrafters/discord#20]
Ubuntu 16.04. Installed from snap.

Discord crashes at startup with:

failed to create prefix path: /tmp/snap.rootfs_3knyfv/var/lib/snapd/lib/vulkan/icd.d: Permission denied

Tried reinstalling, purging configurations and installing mesa-vulkan-drivers. No help.
The files that the discord seems to be looking for are located at
/usr/share/vulkan/icd.d

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting everyone!!

This appears to be fixed now in the latest version of the snap, so I'm closing this issue now. Please comment if this is not the case.
