### ISSUE TITLE
Font with emoji support missing?

### ISSUE THREAD

**Issue by fosspill** [snapcrafters/discord#22]
It seems like the snap does not include a font with emoji support.

While discord mostly use their own built-in emojis, it is possible that certain people or applications use standard emojis instead. Using the snap you'll only see a square instead of the expected emoji.

**Comment by popey** [comment]
I think there have been improvements in the desktop-gtk desktop helpers we use to wrap the application, but we haven't done a build of discord for 2 months. I'll press the "build" button and we'll get a new revision in the edge channel. Once that's built (should be in an hour or so) could you `snap refresh discord --edge` and see if that fixes it?

If not, is there a recommended font (preferably one that's in the Ubuntu 16.04 archive) we could just bundle in?

**Comment by popey** [comment]
Huh. I underestimated the delay on the launchpad [build](https://launchpad.net/builders) service (currently 9 hours). I'll do a quick build locally and push to the store asap.

**Comment by popey** [comment]
The edge channel has revision 56 which is built with the latest desktop launchers. Feel free to `snap refresh discord --edge` and let us know. I am also running that version so you can ping me example emoji that fail so we can both test.

**Comment by fosspill** [comment]
Stop being so efficient! :) 

I'll test and report back. I've also searched for fonts with emoji support for 16.04, but I'm unsure of what would be the best choice...

**Comment by popey** [comment]
To be honest we can likely yank in a deb from somewhere else and dump it in. However as I understand it this should all be fixed with the latest build - if not we need to report the isssue to the desktop helper people.

**Comment by fosspill** [comment]
After some testing, this seems to only happen when done through their api instead of the client. While this might be possible to "fix" but adding a font with emoji support. It's very much a rare edge case and I do not see the need in fixing it here. Discord however should make their api do the same emoji change for their api as they do with the client.
