### ISSUE TITLE
[Bug]: Notifications Are Problematic 

### ISSUE THREAD

**Issue by XRomieo** [snapcrafters/discord#221]
### What happened?

Yesterday the new version of discord released on August 2nd, 2024 and in that version the notifications are messed up. In the previous version the image of the person sending the message was also shown and at the top it was written that this notification from discord. But now the image of the person is not showing and at the top it say's the notification is from an unknown application
![Screenshot from 2024-08-03 11-22-21](https://github.com/user-attachments/assets/803a3744-1afb-4b23-b08b-58cd9b2a37dd)

### What should have happened?

I don't know what could have happened.

### Output of `snap info discord`

```shell
name:      discord
summary:   Chat for Communities and Friends
publisher: Snapcrafters✪
store-url: https://snapcraft.io/discord
contact:   https://github.com//snapcrafters/discord/issues
license:   Proprietary
description: |
  Discord is the easiest way to communicate over voice, video, and text.
  Chat, hang out, and stay close with your friends and communities.
  
  Snaps are confined, as such Discord may be unable to perform some of the
  tasks it typically does when unconfined. This may result in the system log
  getting spammed with apparmor errors. Granting access to the system-observe
  interface when in the snap will enable the features, and thus reduce the
  logging.
  
    snap connect discord:system-observe
  
  **Authors**
  
  This snap is maintained by the Snapcrafters community, and is not
  necessarily endorsed or officially maintained by the upstream developers.
commands:
  - discord
snap-id:      qHVefGEBezeuCeSfTND40uoUD6GRw8BO
tracking:     latest/stable
refresh-date: today at 10:28 PKT
channels:
  latest/stable:    0.0.62 2024-08-02 (201) 117MB -
  latest/candidate: 0.0.62 2024-08-02 (201) 117MB -
  latest/beta:      ↑                             
  latest/edge:      ↑                             
installed:          0.0.62            (201) 117MB -
```

### Output of `snap connections discord`

```shell
Interface               Plug                            Slot                            Notes
audio-playback          discord:audio-playback          :audio-playback                 -
audio-record            discord:audio-record            :audio-record                   -
camera                  discord:camera                  :camera                         -
content[gnome-46-2404]  discord:gnome-46-2404           gnome-46-2404:gnome-46-2404     -
content[gpu-2404]       discord:gpu-2404                mesa-2404:gpu-2404              -
content[gtk-3-themes]   discord:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    discord:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   discord:sound-themes            gtk-common-themes:sound-themes  -
desktop                 discord:desktop                 :desktop                        -
desktop-legacy          discord:desktop-legacy          :desktop-legacy                 -
gsettings               discord:gsettings               :gsettings                      -
home                    discord:home                    :home                           -
mount-observe           discord:mount-observe           -                               -
network                 discord:network                 :network                        -
network-observe         discord:network-observe         -                               -
opengl                  discord:opengl                  :opengl                         -
process-control         discord:process-control         -                               -
removable-media         discord:removable-media         -                               -
screen-inhibit-control  discord:screen-inhibit-control  :screen-inhibit-control         -
shared-memory           discord:shmem                   :shared-memory                  -
system-observe          discord:system-observe          -                               -
unity7                  discord:unity7                  :unity7                         -
wayland                 discord:wayland                 :wayland                        -
x11                     discord:x11                     :x11
```

### Output of `snap version`

```shell
snap    2.63+24.04ubuntu0.1
snapd   2.63+24.04ubuntu0.1
series  16
ubuntu  24.04
kernel  6.8.0-39-generic
```

**Comment by jnsgruk** [comment]
Hi, thanks for the report. I've asked internally to see if our desktop team have seen anything similar and will report back soon.

**Comment by 3v1n0** [comment]
Is the FDO notifications backend in use? IIRC the desktop launcher should force it by using `GNOTIFICATION_BACKEND=freedesktop`.

**Comment by jnsgruk** [comment]
Ah interesting - I don't know, but I'd have assumed that would be a feature of the gnome extension if needed?

(cc @sergiusens)

**Comment by jnsgruk** [comment]
@3v1n0 - looks like it does in fact set that env var:

![image](https://github.com/user-attachments/assets/f2a2df73-3add-4fa0-862c-bd031fdcaf2a)

**Comment by soumyaDghosh** [comment]
It has something to do with `snapd`, probably. Might be similar to [this](https://github.com/snapcore/snapd-desktop-integration/pull/86) or something else. But, it's definitely related to `snapd`

**Comment by aleasto** [comment]
Thanks to chromium devtools within electron this can be easily tested: _(sorry, using Mattermost here but it's the same bug)_

core22:
```
method call time=1723024886.396622 sender=:1.467 -> destination=:1.41 serial=20 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Mattermost"
   uint32 0
   string ""
   string "Test"
   string ""
   array [
      string "default"
      string "View"
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "mattermost-desktop_Mattermost"
      )
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 -1
```

core24:
```
method call time=1723024745.577356 sender=:1.97 -> destination=org.freedesktop.Notifications serial=630 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string ""
   uint32 0
   string ""
   string "Test"
   string ""
   array [
      string "default"
      string ""
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "snap.mattermost-desktop"
      )
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 -1
```

**Comment by soumyaDghosh** [comment]
> Thanks to chromium devtools within electron this can be easily tested: _(sorry, using Mattermost here but it's the same bug)_
> 
> core22:
> ```
> method call time=1723024886.396622 sender=:1.467 -> destination=:1.41 serial=20 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
>    string "Mattermost"
>    uint32 0
>    string ""
>    string "Test"
>    string ""
>    array [
>       string "default"
>       string "View"
>    ]
>    array [
>       dict entry(
>          string "desktop-entry"
>          variant             string "mattermost-desktop_Mattermost"
>       )
>       dict entry(
>          string "urgency"
>          variant             byte 1
>       )
>    ]
>    int32 -1
> ```
> 
> core24:
> ```
> method call time=1723024745.577356 sender=:1.97 -> destination=org.freedesktop.Notifications serial=630 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
>    string ""
>    uint32 0
>    string ""
>    string "Test"
>    string ""
>    array [
>       string "default"
>       string ""
>    ]
>    array [
>       dict entry(
>          string "desktop-entry"
>          variant             string "snap.mattermost-desktop"
>       )
>       dict entry(
>          string "urgency"
>          variant             byte 1
>       )
>    ]
>    int32 -1
> ```

So, in `core22` the name of the desktop file itself is sent, where as in `core24`, the `x-snapInstance` is sent.

**Comment by aleasto** [comment]
Also the first field "app_name" is empty

**Comment by soumyaDghosh** [comment]
> Also the first field "app_name" is empty

Thanks a lot for your help and taking your time. This is a great lead. We'll surely found the coz soon

**Comment by jnsgruk** [comment]
Hi all, I've just released a new revision into `latest/candidate` that should fix this. Can you give it a test with:

```
sudo snap refresh discord --channel latest/candidate
```

And post your results in #223?

**Comment by jnsgruk** [comment]
This should now be fixed, thanks for your patience all!
