### ISSUE TITLE
Why are so many libs included?

### ISSUE THREAD

**Issue by simoniz0r** [snapcrafters/discord#24]
I was having a look through the snap of Discord and noticed that there are ***a lot*** of libs included.  Why is this?  Most of the libs look like they have nothing to do with Discord and would definitely be present on a normal user's install.

Including so many libs *might* be the reason that the snap of Discord doesn't seem to want to follow my system theme (and also cause other problems with incompatibilities with the system and those libs).

**Comment by popey** [comment]
Hi @simoniz0r we could certainly trim down a few, but we can't guarantee that they all exist on all installs that snaps work on, so we bundle the ones needed for discord to run properly. If you can highlight some you think we shouldn't ship, I'd be happy to do some test builds without them to reduce the number down.

**Comment by flexiondotorg** [comment]
This issue was resolved via https://github.com/snapcrafters/discord/commit/04578014c217d999fa955958d52277ace6e2f7f5
