### ISSUE TITLE
Discord Rich Presence doesn't work with the Snap images

### ISSUE THREAD

**Issue by Almighty-Alpaca** [snapcrafters/discord#25]
When trying to use any [Discord RPC](https://github.com/discordapp/discord-rpc) enabled application together with the Snap images of Discord the rich presence doesn't show up. As soon as you switch to the Debian package provided by Discord [on their website](https://discordapp.com/download) everything works as expected.

Tested on Ubuntu 18.04 LTS with Discord Snap Version 0.0.4

**Comment by kryptodev** [comment]
Can verify this issue a month after it was originally posted. Regards.

**Comment by Fuseteam** [comment]
seems related to #2 and #23

**Comment by Blackop778** [comment]
This seems to still be a problem. Could this get looked into?

**Comment by Fuseteam** [comment]
@Blackop778 check the linked issues might offer some workaround for you
most notable the system-observe connection

**Comment by Fuseteam** [comment]
seems to work with the system-observe connection
@Blackop778 @Almighty-Alpaca @iMaxopoly can you guys try running `sudo snap connect discord:system-observe` to see if it resolves the issue?

**Comment by popey** [comment]
I've tested with `system-observe` enabled, and this does indeed work.

**Comment by Feichtmeier** [comment]
It works for spotify snap <-> discord snap
But it does not work for code snap <-> discord snap
Maybe there is something more needed for classic snaps?

**Comment by Feichtmeier** [comment]
Tested also with intellij and android-studio - discord rich presence does really not work. Would be great if this could be somehow fixed and I think this issue needs to be re-opened
CC @kenvandine

**Comment by Feichtmeier** [comment]
Sorry for the poke, but this issue is sadly still remaining. While the rich presence of other confined snaps like spotify can be seen in the discord snap, the connection to the vscode and intellij snaps rich presence is still not working. I would thus vote to re-open this issue

**Comment by diddledani** [comment]
Per [discord/discord-rpc](https://github.com/discord/discord-rpc) the IPC uses a UNIX socket in `$XDG_RUNTIME_DIR` which is unique to each statically confined snap - The reason that snaps in classic confinement work is because they use your normal `$XDG_RUNTIME_DIR`:

- https://github.com/discord/discord-rpc/blob/963aa9f3e5ce81a4682c6ca3d136cddda614db33/src/connection_unix.cpp#L68
- https://github.com/discord/discord-rpc/blob/963aa9f3e5ce81a4682c6ca3d136cddda614db33/src/connection_unix.cpp#L31

**Comment by Feichtmeier** [comment]
Noticed today that the discord snap rich presence now works with this extension! 🥳 
https://marketplace.visualstudio.com/items?itemName=LeonardSSH.vscord this works in the 
So I guess it must depend on how it is implented and from the snap side it seems to work I guess 🤷 
I don't know if this actually can help you with your intellij presence extension @Almighty-Alpaca

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting this, everyone!

Closing this issue again, as it seems to be fixed according to @Feichtmeier 's comment. If you find apps where it's not working, please comment and we can reopen this issue!
