### ISSUE TITLE
SnapD containement malfonctioning?

### ISSUE THREAD

**Issue by ghost** [snapcrafters/discord#26]
sudo snap disconnect discord:process-control core:process-control
sudo snap disconnect discord:system-observe core:system-observe

Both tell me that these are not connected but Discord still sees the processes on my computer? :thinking:

**Comment by Simon-Laux** [comment]
I have the same problem, also I'd like a permission to deny discord reading all my keystrokes(when its in in the background). This permission needed for the hotkey function could be abused to a keylogger with a malicious update.

**Comment by merlijn-sebrechts** [comment]
What distro are you using? Snap confinement does not work completely on a number of distributions such as Fedora.

**Comment by Simon-Laux** [comment]
> I have the same problem, also I'd like a permission to deny discord reading all my keystrokes(when its in in the background). This permission needed for the hotkey function could be abused to a keylogger with a malicious update.

probably was because of using X server, I think wayland fixes that all apps can read every keystroke


I think we can close this as the OP deleted their account and thus won't answer.

**Comment by merlijn-sebrechts** [comment]
Ok, thanks for the info!
