### ISSUE TITLE
Snap seems to be out of date

### ISSUE THREAD

**Issue by j3gb3rt** [snapcrafters/discord#27]
Getting Discord window saying 'Update is available' on startup

Dropdown options are 'deb', 'tar.gz', 'I'll figure it out'

**Comment by SirRujak** [comment]
I had the same issue. I have temporarily gotten around it by uninstalling and reinstalling the snap. The new version is giving me an error every time I restart my machine though so you may want to stick with the older version.

**Comment by popey** [comment]
Are you still getting this? Our snap is up to date with upstream. Try `snap refresh discord` to force refresh the application.

**Comment by SirRujak** [comment]
```
mkdir: cannot create directory '/home/USER/snap/discord/66/.local': Permission denied
mkdir: cannot create directory '/home/USER/snap/discord/66/.config': Permission denied
/snap/discord/66/bin/desktop-launch: line 177: /home/USER/snap/discord/66/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/USER/snap/discord/66/.config/': Not a directory
```

That is the error I am still getting after every reboot of the machine. There are a bunch of other permission denied errors but those are the first three and all the others seem to have the same source. Some extra info:

Distro: Solus
snap: 2.32.6
snapd: 2.32.6
series: 16
solus: 3.9997
kernel: 4.15.18-67

Discord info:
version: 0.0.5
revision: 66
tracking: stable
developer: snapcrafters

**Comment by popey** [comment]
Can you try `snap remove discord` and then `snap install discord`. This will force you to login to discord again.

**Comment by SirRujak** [comment]
That will indeed allow it to work as long as I don't reboot my computer. After a restart it gives me the permission errors again.

**Comment by popey** [comment]
Huh. I wonder if the permissions got screwed somehow. Did you ever run it under sudo?
What are the permissions on that folder? here's mine.

```
$ ls -ld ~/snap/discord/66/.local/
drwxr-xr-x 3 alan alan 4096 Feb 15 21:55 /home/alan/snap/discord/66/.local/
```

**Comment by SirRujak** [comment]
I just reinstalled then restarted to get everything. Both before restart(but after reinstall when things still work) and after a restart I get this:
```
$ ls -ld ~/snap/discord/66/.local/
drwxrwxr-x 3 rujak rujak 4096 May 25 13:49 /home/rujak/snap/discord/66/.local/
```

Also, after restart, when I tried to open discord, the first error that appears is actually:
```
/snap/discord/66/bin/desktop-launch: line 177: /home/rujak/snap/discord/66/.config/user-dirs.dirs: Permission denied
```

**Comment by SirRujak** [comment]
I ended up fully uninstalling snapd and wiping all of my user data for it other than some steam games I backed up. After a restart and reinstalling snapd followed by the discord snap everything has been working since. I'm guessing that some config file was broken somewhere along the way but sadly I don't have much else to suggest.

**Comment by MadeByNC** [comment]
yes, and reinstalling discord doesnt help.

from today

snap install discord
discord 0.0.5 from Snapcrafters installed

**Comment by simonsolberg** [comment]
I had the same issue. Refreshing didn't do anything. Reinstalling worked.

**Comment by Fuseteam** [comment]
isn't that due to the fix in #53 and #49 if so shouldn't this issue be closed?

**Comment by popey** [comment]
I believe discord is now fixed (the revision in the store [which I just tested again]) works fine. If there's new issues, please open a new issue :D

**Comment by Fuseteam** [comment]
that sounds like issue #54 might be one of those shiny new issues :P

**Comment by Geo1088** [comment]
Having similar problems today, Discord prompts me to install 0.0.10, current version is 0.0.9. `snap reload discord` didn't help, just replied "no updates available". Reinstalling just reinstalled 0.0.9 which prompted me to update again.

**Comment by popey** [comment]
I just hit the rebuild button. Let's see if we get a 0.0.10 out of it! :D

**Comment by popey** [comment]
0.0.10 has been in stable for a few hours now. all seems well.

**Comment by Geo1088** [comment]
Late reply, but all's well on my end now! Cheers
