### ISSUE TITLE
Launch failure - failed to create symbolic link gtkfilechooser.ini

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/discord#31]
```
$ snap run discord
/snap/discord/64/bin/desktop-launch: line 23: /home/adam/.config/user-dirs.dirs: Permission denied
ln: failed to create symbolic link '/home/adam/snap/discord/64/.config/gtk-2.0/gtkfilechooser.ini': File exists
```

I also have the Deb installed.

<details>
<summary>Discord 0.0.5 (65)</summary>

```
$ snap info discord
tracking:  stable
refreshed: 2018-05-09T20:15:40+01:00
installed:   0.0.5 (64) 140MB -
$ snap version
snap    2.32.8+18.04
snapd   2.32.8+18.04
series  16
ubuntu  18.04
kernel  4.15.0-20-generic
$ snap info core
tracking:  beta
refreshed: 2018-05-11T15:51:12+01:00
installed:   16-2.32.8                (4650) 90MB core
```

</details>

**Comment by Ads20000** [comment]
[This seems to be a snapd issue though I'm not sure how to debug it.](https://forum.snapcraft.io/t/seemingly-random-snap-disconnections-and-breakage/5292/3)

**Comment by statico** [comment]
In case people find this while googling, the thread linked above mentions a fix that worked for me:

```
snap revert core
snap refresh core
```

**Comment by AlexisWilke** [comment]
@statico Why would you reset `core` and not your own tool (`discord`)?

**Comment by statico** [comment]
@AlexisWilke I don't remember. This was so long ago that I don't even know what those commands do.
