### ISSUE TITLE
Cannot open links

### ISSUE THREAD

**Issue by Krotera** [snapcrafters/discord#34]
Reviving [#1](https://github.com/snapcrafters/discord/issues/1) on Kubuntu 18.04. Did stuff break again?

Like that thread's OP, I have `snapd-xdg-open` installed, and `xdg-open [url]` works in a console, yet clicking any links in Discord that would normally open in the browser does nothing.

**Comment by liberodark** [comment]
Hi me too on manjaro but later this new update work and have install no snap version and link work.
Please fix that.

Thank

**Comment by mmtrt** [comment]
same issue here which is very annoying.

cc @flexiondotorg @popey

**Comment by popey** [comment]
Are there any messages on the console if you launch discord in a terminal and try to click a link? Is there anything in `dmesg`? I'm not seeing the issue here on Ubuntu 18.04.

**Comment by mmtrt** [comment]
@popey when clicking on url

> /snap/discord/66/usr/bin/xdg-open: 566: /snap/discord/66/usr/bin/xdg-open: kde-open5: not found
>

**Comment by Krotera** [comment]
@popey Same message as @mmtrt had: `/snap/discord/66/usr/bin/xdg-open: 566: /snap/discord/66/usr/bin/xdg-open: kde-open5: not found`

@mmtrt I do not understand your solution. Can you explain how to unstage a package?

**Comment by mmtrt** [comment]
@Krotera That solution will work only when building this snap, so if you want the fix faster then clone this repo and locally build this snap with the mentioned line removed from `snapcraft.xml`.

**Comment by mmtrt** [comment]
can you fix this issue with my posted solution above. cc @popey

**Comment by popey** [comment]
Ok, I have removed xdg-open via a prime step, rather than removing the entire xdg-utils package. The xdg-utils package was added because without it discord spams the terminal looking for xdg-mime. This should build shortly, so if you want to test via `snap refresh discord --edge` - when build 70 appears under `snap info discord` and let us know if that works, that would be awesome, thanks!

**Comment by mmtrt** [comment]
@popey just locally tested discord with that file removed it fixes this issue.

**Comment by popey** [comment]
Ok, thanks for testing! I've pushed that to stable.
