### ISSUE TITLE
Emojis at channel names doesn't appear

### ISSUE THREAD

**Issue by thiras** [snapcrafters/discord#35]
I think it's similar issue with #30 

It's works smooth on chrome
![screenshot from 2018-06-20 20-55-43](https://user-images.githubusercontent.com/5150432/41675972-dc54c6be-74cc-11e8-863f-79e407fd7708.png)

And this is the Discord snap package on the same OS
![screenshot from 2018-06-20 20-55-21](https://user-images.githubusercontent.com/5150432/41675993-e8d224cc-74cc-11e8-97fa-adffba57475e.png)

So definitely it's not an OS related issue. Probably the snap package has some missing parts for emojis

**Comment by Fuseteam** [comment]
chrome as in the chrome browser?
pretty sure it's a problem with the discord app itself rather then the snap

**Comment by thiras** [comment]
> chrome as in the chrome browser?

Yes Google's Chrome through their apt repository. I also confirm there is no issue at Firefox too.

Ubuntu 18.04

**Comment by Fuseteam** [comment]
yep it's the difference between the browser version and the app version of discord

**Comment by Fragstiller** [comment]
Its problem with the snap. In discord installed from deb package emoji in channel names work just fine.

**Comment by Fuseteam** [comment]
pretty sure it does if it doesn't it probably a font issue on your machine, it appears just fine on my snap package as well as of discord 0.0.5 revision 73
![image](https://user-images.githubusercontent.com/10421851/44954965-b37b0c00-ae81-11e8-97a5-c041ae7a8110.png)

**Comment by Fragstiller** [comment]
It started appearing on my machine too. Maybe it's because I installed windows fonts exported from Win10 iso. Anyway, seems like it was fixed and now only occurs because of local font issues.

**Comment by Fuseteam** [comment]
i believe i installed the google noto fonts on my machine some time ago......might be a factor

**Comment by gargoyle** [comment]
Any updates on this? In chrome, emoji in names works:-
![image](https://user-images.githubusercontent.com/437990/46076021-3db64780-c184-11e8-9d03-dadb9d8af0a9.png)

But in the snap, it's a no, no...
![image](https://user-images.githubusercontent.com/437990/46076047-4e66bd80-c184-11e8-8493-4d04ad3172b1.png)

**Comment by gargoyle** [comment]
Update. Fixed it with the config suggestions from this post:-https://github.com/wireapp/wire-desktop/issues/622#issuecomment-300101249

![image](https://user-images.githubusercontent.com/437990/46077773-f6cb5080-c189-11e8-94d8-322f60d939d5.png)

It's using a different emoji font for the names than the message text, but I can live with that. It's also fixed other apps that were struggling with emoji.

Probably a bit off-topic for here, but can't something like this be rolled directly into ubuntu/gnome?

**Comment by lekseven** [comment]
> i believe i installed the google noto fonts on my machine some time ago......might be a factor

Yep. Removing the noto fonts fixed the issue in my case.
