### ISSUE TITLE
Link not opening in browser when clicked

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [snapcrafters/discord#38]
Whenever I click on a link in discord, nothing happens. Nothing is opened in the browser.

If I use the discord debian package, all good.

I'm not sure what's causing this only with the snap version. I'm on Kubuntu 18.04 and use google chrome (install from apt).

I'd love some direction on how to debug this. I know there is very little information, so it's a hard guess.

**Comment by Sslaxx** [comment]
Don't think this is a Snap-only bug - running into this issue using the official deb packages from the Discord site.

**Comment by Fire-Dragon-DoL** [comment]
I swapped between the two and the official package works perfectly for me @Sslaxx

**Comment by Fuseteam** [comment]
Snap worked perfectly for me tho

**Comment by MuffinCollector** [comment]
Installing xdg-utils (in arch) fixed this for me.

**Comment by Fire-Dragon-DoL** [comment]
That can explain the problem. In Kubuntu there is currently a bug where xg-utils doesn't work, unless you install conqueror (which is not default)

**Comment by Emulle** [comment]
I have the same problem(arch), I do believe my problem started when I installed Chrome/Chromium to try a few things out(my default browser is Firefox) and no no links will work any more.  
I'd very much appreciate any help fixing this issue.

**Comment by Storm-Engineer** [comment]
Also having this on Arch, and it's not only links but anything, including viewing the original of images.

It just started on its own, though Chrome was installed already before that so could still be related.

**Comment by Fuseteam** [comment]
i do not have this issue fwiw

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting everyone!!

This appears to be fixed now in the latest version of the snap, so I'm closing this issue now. Please comment if this is not the case.
