### ISSUE TITLE
Discord AppIndicator not working on Ubuntu 17.04

### ISSUE THREAD

**Issue by Ads20000** [snapcrafters/discord#4]
The Discord AppIndicator doesn't work out-of-the-box on Ubuntu 17.04. As I said [here](https://forum.snapcraft.io/t/snap-wishlist-suggestions-wanted/567/39), I think the likely reason is because Ubuntu changed the value of `XDG_CURRENT_DESKTOP` from `Unity` to `Unity:Unity7` for Ubuntu 17.04.

@flexiondotorg 's [patch for the Dropbox Deb](https://launchpadlibrarian.net/312989622/nautilus-dropbox-fix-unity-indicator-menu.debdiff) was:

```
# Fix indicator icon and menu on Unity environments. (LP: #1559249)
new_env = os.environ.copy()        
if 'Unity' in os.environ.get("XDG_CURRENT_DESKTOP", '').split(":"):
  new_env['XDG_CURRENT_DESKTOP'] = 'Unity'
```

Presumably we could do a similar thing in a scriptlet for the Discord snap?

**Comment by Ads20000** [comment]
[The Ubuntu desktop team are planning to fix this upstream](https://didrocks.fr/2017/08/23/ubuntu-gnome-shell-in-artful-day-7/)

**Comment by jhasse** [comment]
The `XDG_CURRENT_DESKTOP` variable shouldn't be used. Rather check if the DBus interface is available, see https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/74.

**Comment by flexiondotorg** [comment]
Closing this issue since it is an problem in Electron itself, not snaps.

**Comment by Ads20000** [comment]
But we should be able to fix this in the snap? Just as we've (I mean Daniel, of course) fixed the cage transformation crash in GIMP by depending on gegl-0.2?

**Comment by Ads20000** [comment]
But we should be able to fix this in the snap whilst we wait for Electron to fix this? Just as we've (I mean Daniel, of course) fixed the cage transformation crash in GIMP by depending on gegl-0.2?

**Comment by MartinX3** [comment]
Still broken in Ubuntu 16.04 Mate /Linux Mint 18.3

**Comment by x4m3** [comment]
still broken on ubuntu 17.10

**Comment by Ads20000** [comment]
This is now working for me on Ubuntu 18.04! :dancer:

**Comment by tapir** [comment]
Broken on ArchLinux with appindicator extension.

Whats wrong with appindicator that half of the applications doesn't work? What a mess.

Is there anything that can be done on Discord side while upstream fixes its shit?

**Comment by Torbrex** [comment]
On Ubuntu, still broken
