### ISSUE TITLE
Proxy settings ?

### ISSUE THREAD

**Issue by fusion4bass** [snapcrafters/discord#41]
Hi,

Discord completely ignores proxy environment variables thus doesn't work behind a proxy.

Log:
> (Discord:41366): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
[WebContents] did-fail-load -105 ERR_NAME_NOT_RESOLVED retry in 1000 ms
[WebContents] retrying load https://discordapp.com/app?_=1536857809179
[WebContents] did-fail-load -105 ERR_NAME_NOT_RESOLVED retry in 1719.915786628663 ms

Version:
> snap    2.35-1.fc28
snapd   2.35-1.fc28
series  16
fedora  28
kernel  4.17.5-200.fc28.x86_64

**Comment by landswim** [comment]
That's a long long story.
The conclusion is that discord doesn't f**k care about any proxies by design.
see this: [discord commuity request](https://support.discord.com/hc/en-us/community/posts/360030200871-You-should-give-a-Proxy-settings-for-the-Windows-version-of-Discord-to-cover-Chinese-users)

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting this!

As this is an issue in Discord itself, and not the Snap, we can't do much about it. Once Discord itself supports proxies, it should work in the snap without issue.
