### ISSUE TITLE
On install discord has autostart enabled in the UI, but the autostart desktop file is missing

### ISSUE THREAD

**Issue by chipaca** [snapcrafters/discord#46]
On install, under settings, the checkbox under Linux Settings -> System startup behaviour is enabled, but
```
$ grep -r X-GNOME ~/snap/discord/
$ 
```
then you disable it and
```
$ grep -r X-GNOME ~/snap/discord/
/home/john/snap/discord/79/.config/autostart/discord-stable.desktop:X-GNOME-Autostart-enabled=false
$ 
```
and then enable it again
```
$ grep -r X-GNOME ~/snap/discord/
/home/john/snap/discord/79/.config/autostart/discord-stable.desktop:X-GNOME-Autostart-enabled=true
$ 
```

**Comment by Fuseteam** [comment]
um wait what's the issue? does it not autostart?

**Comment by chipaca** [comment]
@fuseteam when you first install it the UI says it'll autostart, but it does not. After you've toggled it, it behaves as expected.

**Comment by Fuseteam** [comment]
Ah interesting seems the neccesary file is missing after the initial install
is this exclusive to the snap? or does it also happen with the deb?
