### ISSUE TITLE
v0.0.8 in edge segfaults after first click

### ISSUE THREAD

**Issue by mattiaswerner** [snapcrafters/discord#51]
Last line in terminal output:
Failed to generate minidump.[4632:0100/000000.907082:FATAL:memory.cc(22)] Out of memory. size=32768
Segmentation fault (core dumped)

dmesg:
[ 5677.634701] Discord[22373]: segfault at 4 ip 00007fc6ee48a7ed sp 00007ffd299a2be8 error 4 in libgobject-2.0.so.0.4800.2[7fc6ee456000+52000]

**Comment by Assisneto** [comment]
I have the same problem

**Comment by YamiYukiSenpai** [comment]
Is this on edge?   Mine's running fine so far

**Comment by DheathNone** [comment]
Thanks, lets see if this will do it!

**Comment by popey** [comment]
Tested and this has fixed it. Apologies it was broken for so long.
