### ISSUE TITLE
Discord out of date again

### ISSUE THREAD

**Issue by DheathNone** [snapcrafters/discord#60]
As with the old issue #49 . Discord snap is out of date yet again: 0.0.9 is required and 0.0.8 is currently on snap.

The latest build (0.0.8) seems to be 12 days ago:
https://build.snapcraft.io/user/snapcrafters/discord/479130
Can someone please ran and check the build again?

**Comment by popey** [comment]
Thanks for the nudge. Building now..

**Comment by DheathNone** [comment]
Thanks! 
That was quick response!

Bit sad that there is no good way to do this more automatically.

**Comment by DheathNone** [comment]
Well, they suggest contacting though twitter for a quick question:
https://support.discordapp.com/hc/en-us

Has anyone asked a solution for this?

**Comment by popey** [comment]
@DheathNone This is now built & tested and in the stable channel.
Snaps do actually build automatically every day normally. However, the way we build discord prevents that working. 
We could work around this slightly by triggering a build daily from a cron job or similar. 

Contacting discord themselves won't help, it's not their problem, but ours.

**Comment by Fuseteam** [comment]
what is preventing it from building automatically, and how can we fix it?
