### ISSUE TITLE
Discord desktop notifications stop working

### ISSUE THREAD

**Issue by TeeeeSeeee** [snapcrafters/discord#64]
After about a minute or two the Discord desktop notifications fail to show up.  The notification sound still plays but no notifications are shown.

**Comment by flexiondotorg** [comment]
Notifications are working correctly.

**Comment by katian** [comment]
> After about a minute or two the Discord desktop notifications fail to show up. The notification sound still plays but no notifications are shown.

hello, same behaviour here
Ubuntu 20.04.2 LTS (Focal Fossa)
