### ISSUE TITLE
Give access to some real directory

### ISSUE THREAD

**Issue by danielesegato** [snapcrafters/discord#66]
Hi,

I know I can access the Desktop, Pictures and other stuff.

But I found really annoying that I can't use my real `/tmp` directory from discord.

Is there a way I can map it so that discord can use it?

**Comment by Fuseteam** [comment]
that's a root directory why do want to give it access to that?

**Comment by danielesegato** [comment]
Because it's where I put temporary stuff, so that it is automatically deleted when the system reboots.

I use the tmp directory all the time cause if i save the file somewhere else (say, Pictures or Desktop or whatever) I just clutter my disk with stuff I don't remember what's for and I should go manually delete after doing whatever I needed to do with the temporary thing (which often I forgot to do).

**Comment by danielesegato** [comment]
@Fuseteam your question made me think.

I think it makes more sense for me to setup a tmp folder in my home folder and set `tmpfiles.d` to clean it up too.

**Comment by Fuseteam** [comment]
glad you could resolve it :D
