### ISSUE TITLE
Latest update crashes Warframe when Discord overlay is enabled.

### ISSUE THREAD

**Issue by RobiFerentz** [snapcrafters/discord#7]
See title

**Comment by simoniz0r** [comment]
What overlay are you talking about?  The in game overlay for voice chat and such?  AFAIK, that's not even a thing on the Linux version of Discord...  I see no setting to enable it at all on Discord Canary running on Xubuntu 16.04.

**Comment by RobiFerentz** [comment]
Wrong repo, sorry.
