### ISSUE TITLE
0.0.10 issues

### ISSUE THREAD

**Issue by ghost** [snapcrafters/discord#72]
Video picture does not display with the 0.0.10 update. Also there are some other graphical issues, such as UI buttons appearing weird, avatars not displaying, et cetera.

**Comment by Fuseteam** [comment]
is this still an issue?

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting this! I'm closing the issue as this doesn't seem to be an issue with the latest version anymore. Please reopen if the issue comes back!
