### ISSUE TITLE
Cannot quit discord Fedora 31

### ISSUE THREAD

**Issue by filirnd** [snapcrafters/discord#75]
Hi, i have same problem that was closed in olds versions.
I've this "snap list":
snap list
Name               Version                     Rev   Tracking  Publisher     Notes
core               16-2.43.3                   8689  stable    canonical✓    core
core18             20200124                    1668  stable    canonical✓    base
discord            0.0.10                      109   stable    snapcrafters  -
gnome-3-26-1604    3.26.0.20191114             98    stable    canonical✓    -
gnome-3-28-1804    3.28.0-16-g27c9498.27c9498  116   stable    canonical✓    -
gtk-common-themes  0.1-29-g45e78c5             1474  stable    canonical✓    -
protobuf           3.11.4                      37    stable    stub          classic
spotify            1.1.26.501.gbe11e53b-15     41    stable    spotify✓      -
sublime-text       3211                        85    stable    snapcrafters  classic

But i cannot close discord. If i click on X it remain alive and i must kill the pids on terminal.

**Comment by Fuseteam** [comment]
do you have "minimize to tray" enabled in the app?

**Comment by filirnd** [comment]
Thank you. Your suggest resolve my problem.
