### ISSUE TITLE
Discord freeze my Ubuntu 20.04

### ISSUE THREAD

**Issue by Baktus79** [snapcrafters/discord#77]
Discord freezes my system for a few seconds at regular intervals. I switched to flatpack instead and the problem was gone. I would rather use snap but it makes the system partially useless.

**Comment by Fuseteam** [comment]
what does the logs say when it freezes the system?

**Comment by Havard-SL** [comment]
I have had this issue! I fixed it by installing "Tweaks" (also known as gnome-tweaks), and opening the new "Extensions" program. In there I disabled "Ubuntu Appindicators". No worries, you can easily turn it on again after they have fixed the issue :)

**Comment by gren236** [comment]
Same issue here. Thanks @Havard-SL for the workaround, waiting for the fix!

**Comment by RickAndTired** [comment]
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/241

**Comment by Baktus79** [comment]
I see no difference whether I turn off the app indicator or not. Discord will, for me, make the system slow / laggy after waiting a few minutes after Discord has started up.

I said in my original post that the Flatpak version of Discord did not lag. I was wrong, the same problem occurs there.

**Comment by RickAndTired** [comment]
> I see no difference whether I turn off the app indicator or not. Discord will, for me, make the system slow / laggy after waiting a few minutes after Discord has started up.
> 
> I said in my original post that the Flatpak version of Discord did not lag. I was wrong, the same problem occurs there.

Someone said the Canary build of Discord solved the issue for him

Deb
https://discordapp.com/api/download/canary?platform=linux
Tar.gz
https://discordapp.com/api/download/canary?platform=linux&format=tar.gz

**Comment by gurgl** [comment]
I can confirm what @Baktus79 says. Disabling appindicators does nothing.

**Comment by gren236** [comment]
Getting Canary build of Discord resolved this issue for me. I guess we should just wait for these fixes to appear at regular public build

**Comment by Baktus79** [comment]
Beautiful :1st_place_medal: 
Then it seems that it will be resolved with the next updates :+1:

**Comment by Littlemac123** [comment]
its still happening for me tho on stable flatpack

**Comment by ninjo1** [comment]
It still happens almost a year after the OP. Is this ever gonna be fixed?

**Comment by diddledan** [comment]
Without any reproduction steps, and given that Discord is proprietary meaning we cannot change Discord itself (we can only change the snap packaging), we are stuck because we have no way to verify the problem and determine if it is that snap that is the problem or whether there is an issue with Discord itself.

**Comment by RickAndTired** [comment]
Adding the Permission "Read process and system information" will prevent the massive log spam from apparmor blocking Discord.

I'm not sure if this will help those with issues, but worth a try.

**Comment by leleoveiga** [comment]
> [ubuntu/gnome-shell-extension-appindicator#241](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/241)

**Comment by leleoveiga** [comment]
It still happens. And the problem is exactly this (at least for me):
> [ubuntu/gnome-shell-extension-appindicator#241](https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/241)

Disabling Ubuntu AppIndicators solves the problem!
