### ISSUE TITLE
Notifications not muting when in Do Not Disturb on KDE Plasma

### ISSUE THREAD

**Issue by YamiYukiSenpai** [snapcrafters/discord#78]
When I turn on DnD when in game, Discord won't mute the notification sounds, although I don't get notified about incoming messages (so it works partially).  On another note, Discord notifications, would interrupt any audio currently playing (i.e. music, videos & game audio).

**Comment by pickfire** [comment]
I faced the same issue. It keeps popping sound even though I put plasma in do not disturb.

**Comment by merlijn-sebrechts** [comment]
Hi, thanks for reporting this!

Is this still happening with the latest version? The snap has changed a lot since 2021.

**Comment by danaYatsuta** [comment]
Still occurs with KDE 6.

**Comment by lengau** [comment]
This still happens, but I don't think it's anything over which we have control, as AFAICT this is a Discord behaviour rather than something specific to the snap. I'll report back in a bit after doing some testing.

**Comment by lengau** [comment]
Just confirmed, this is an upstream issue and not a problem with the snap specifically. The app will send a notification as expected, but doesn't check whether notifications are inhibited on dbus before playing the notification audio.

I've [made an upstream feature request](https://support.discord.com/hc/en-us/community/posts/22549582088343-Respect-desktop-s-Do-Not-Disturb-mode-for-desktop-notifications) for this, which is unfortunately the best we can do. I would suggest that anyone who's affected by this (as I am too) show their support for a fix upstream.
