### ISSUE TITLE
fonts missing

### ISSUE THREAD

**Issue by Fuseteam** [snapcrafters/discord#8]
i have noticed certain fonts are missing in the snap version
![image](https://user-images.githubusercontent.com/10421851/32523592-b9632552-c3fa-11e7-9c13-3e78fb153099.png)
![image](https://user-images.githubusercontent.com/10421851/32523629-e53380aa-c3fa-11e7-814d-1418a0d6f483.png)

**Comment by popey** [comment]
Do you know which ones you're using to render those characters outside of the snap?

**Comment by Fuseteam** [comment]
no i don't sadly

**Comment by popey** [comment]
What version of snapd are you on? Paste the output of `snap version`. Thanks.

**Comment by Fuseteam** [comment]
![image](https://user-images.githubusercontent.com/10421851/32671138-10f777ce-c625-11e7-875a-57091d4a7455.png)
this?

**Comment by Fuseteam** [comment]
this? snap    2.28.5
snapd   2.28.5
series  16
ubuntu  16.04
kernel  4.10.0-38-generic

**Comment by simoniz0r** [comment]
Noto Sans CJK is what most people use to have those characters work properly.

Also, either noto-fonts-emoji or ttf-symbola should probably be included for additional emoji support.

**Comment by thefirstofthe300** [comment]
I am seeing this issue on both stock Ubuntu 17.10 and stock Ubuntu 16.04 installs. I haven't touched any font settings. Gnome Terminal, Firefox, Chrome, and Atom (installed from the snap as well although unsandboxed) can successfully render the character I am having issues with (Unicode symbol 0x30C4).

Output of snap version:
```
snap    2.29.3
snapd   2.29.3
series  16
ubuntu  16.04
kernel  4.10.0-38-generic
```

**Comment by popey** [comment]
I have added the font to the discord build, but we have a datacentre outage right now so it's probably not going to build for a few hours at least. I'll keep an eye on it, and will comment in here once there is a build you can test.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/snapcrafters/discord/commit/6e197f2f3f3e94a94405f4e3e51624b181b8d76a

**Comment by WinterPhoenix96** [comment]
Right, so, this does not appear to be fixed, at least on Ubuntu 18.04.

`snap version` gives:
```
snap    2.34.3
snapd   2.34.3
series  16
ubuntu  18.04
kernel  4.15.0-30-generic
```

Fresh install of both Ubuntu and Discord's snap application. Appears fine if I open Discord in Chrome, but not in the snap application.

**Comment by Sophie-bear** [comment]
Seems to be working fine on a .DEB install here, but I also encountered this issue on the snap version.

**Comment by AngelCrawford** [comment]
Had the same problem as @Sophie-bear. Fixed it with:
`$ sudo apt-get install ttf-ancient-fonts`

`snap 2.34.3   snapd 2.34.3   series 16   ubuntu 18.04   kernel 4.15.0-32-generic`
