### ISSUE TITLE
Spamming syslog

### ISSUE THREAD

**Issue by gurgl** [snapcrafters/discord#80]
My /var/log/syslog is completely spammed with below messages on ubuntu 20.04. I suspect its also guilty of freezing my system up occasionally.

> Jul  5 20:45:03 kalle-System-Product-Name kernel: [65070.054788] audit: type=1400 audit(1593974703.723:1212275): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/proc/1369/cmdline" pid=127060 comm="Discord" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> Jul  5 20:45:03 kalle-System-Product-Name kernel: [65070.054791] audit: type=1400 audit(1593974703.723:1212276): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:03 kalle-System-Product-Name kernel: [65070.054808] audit: type=1400 audit(1593974703.723:1212277): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:03 kalle-System-Product-Name kernel: [65070.054828] audit: type=1400 audit(1593974703.723:1212278): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:03 kalle-System-Product-Name kernel: [65070.054847] audit: type=1400 audit(1593974703.723:1212279): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/proc/1383/cmdline" pid=127060 comm="Discord" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> Jul  5 20:45:03 kalle-System-Product-Name kernel: [65070.054855] audit: type=1400 audit(1593974703.723:1212280): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:03 kalle-System-Product-Name kernel: [65070.054871] audit: type=1400 audit(1593974703.723:1212281): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:03 kalle-System-Product-Name kernel: [65070.054888] audit: type=1400 audit(1593974703.723:1212282): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056413] kauditd_printk_skb: 106 callbacks suppressed
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056415] audit: type=1400 audit(1593974708.723:1212389): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056437] audit: type=1400 audit(1593974708.723:1212390): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/proc/1369/cmdline" pid=127060 comm="Discord" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056441] audit: type=1400 audit(1593974708.723:1212391): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056459] audit: type=1400 audit(1593974708.723:1212392): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056477] audit: type=1400 audit(1593974708.723:1212393): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056498] audit: type=1400 audit(1593974708.723:1212394): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/proc/1383/cmdline" pid=127060 comm="Discord" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056501] audit: type=1400 audit(1593974708.723:1212395): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056519] audit: type=1400 audit(1593974708.723:1212396): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056535] audit: type=1400 audit(1593974708.723:1212397): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:08 kalle-System-Product-Name kernel: [65075.056552] audit: type=1400 audit(1593974708.723:1212398): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058469] kauditd_printk_skb: 108 callbacks suppressed
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058471] audit: type=1400 audit(1593974713.727:1212507): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058484] audit: type=1400 audit(1593974713.727:1212508): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058505] audit: type=1400 audit(1593974713.727:1212509): apparmor="DENIED" operation="open" profile="snap.discord.discord" name="/proc/1383/cmdline" pid=127060 comm="Discord" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058514] audit: type=1400 audit(1593974713.727:1212510): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058531] audit: type=1400 audit(1593974713.727:1212511): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058548] audit: type=1400 audit(1593974713.727:1212512): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058564] audit: type=1400 audit(1593974713.727:1212513): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058579] audit: type=1400 audit(1593974713.727:1212514): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058595] audit: type=1400 audit(1593974713.727:1212515): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
> Jul  5 20:45:13 kalle-System-Product-Name kernel: [65080.058611] audit: type=1400 audit(1593974713.727:1212516): apparmor="DENIED" operation="ptrace" profile="snap.discord.discord" pid=127060 comm="Discord" requested_mask="read" denied_mask="read" peer="unconfined"
>

**Comment by Fuseteam** [comment]
have made a search for similar issues? i am positive this is a duplicate

**Comment by RickAndTired** [comment]
You can turn off the UbuntuAppindicator extension to solve this for now

https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/241

**Comment by gurgl** [comment]
If you mean the the Ubuntu "tweaks" setting "Ubuntu appindicators". No, disabling that does nothing for me. The above shit keeps pouring in. I disabled it, restarted Discord. Same thing.

**Comment by gurgl** [comment]
Ok, so what did work was installing the Discord Cannary release. Now my syslog is quiet.

**Comment by Fuseteam** [comment]
you haven't looked into the existing issues did you :eyes:
