### ISSUE TITLE
Version 0.0.11 available, can't open with 0.0.10

### ISSUE THREAD

**Issue by Nightmayr** [snapcrafters/discord#82]
When I launch discord, it informs me that there is a new version 0.0.11 available and provides the option of downloading the deb or a tarball. I'm unable to bypass the prompt to download the new version, therefore being unable to use the application.

**Comment by Fuseteam** [comment]
i tried to trigger a rebuild with #83

**Comment by Fuseteam** [comment]
well looks like that failed lol

**Comment by jrabbitb** [comment]
workaround (sort of): use discord.com while we wait for an updated snap package.

**Comment by Nightmayr** [comment]
Looks like the travis job definition needs updating to run snapcraft without sudo. Error message from @Fuseteam rebuild attempt `'sudo' cannot be used with build provider 'lxd'`

**Comment by jrabbitb** [comment]
I see the 0.0.0.11 updated posted. installed and working for me. thanks!

**Comment by Nightmayr** [comment]
Yep I also see the 0.0.11 update, working for me as well. Closing this issue

**Comment by Fuseteam** [comment]
> Looks like the travis job definition needs updating to run snapcraft without sudo. Error message from @Fuseteam rebuild attempt `'sudo' cannot be used with build provider 'lxd'`

ohw interesting
