### ISSUE TITLE
[question]how are the discussions with upstream

### ISSUE THREAD

**Issue by Fuseteam** [snapcrafters/discord#86]
i've seen the "discussing with upstream" tag for a while, i was wondering how close we are to getting this format picked up with the upstream for easier updates

**Comment by MMachado05** [comment]
Yeesh, I assumed that was a recent change to the readme, but I wasn't aware that it's said that for 3 years now. I guess discussions aren't going great...

**Comment by popey** [comment]
I don't believe we had any further conversations since then. So there's likely nothing to report.
