### ISSUE TITLE
discord has updated to 0.0.12

### ISSUE THREAD

**Issue by Fuseteam** [snapcrafters/discord#87]
i have reopened my #83 pullrequest in an attempt to bump the build. the build succeeded this time in contrast to the last time

**Comment by zdarova6882** [comment]
hi

**Comment by zdarova6882** [comment]
it's time for 0.0.12

**Comment by Tyrewt** [comment]
Opening Discord 0.0.11 (snap package) an update is suggested for version 0.0.12 but the package isn't available in Ubuntu 20.04.1 Repo, resulting in the application closing/suggesting manual download. 

latest/stable:    0.0.11 2020-08-06 (112)

**Comment by Fuseteam** [comment]
as it is now resolved; closing issue
