### ISSUE TITLE
some sort of a watcher for version number update

### ISSUE THREAD

**Issue by Fuseteam** [snapcrafters/discord#89]
could we have some sort of watcher for a version number change to trigger an snap update?
curling https://discordapp.com/api/download?platform=linux&format=deb seems to contain the version number in the output:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="https://dl.discordapp.net/apps/linux/0.0.12/discord-0.0.12.deb">https://dl.discordapp.net/apps/linux/0.0.12/discord-0.0.12.deb</a>.  If not click the link.
```

**Comment by Fuseteam** [comment]
i could try this if i knew where to look in the packaging

**Comment by a-skuba** [comment]
Seems like they already have some watcher in place.

Yesterday, 4/12/2020 at 23:06 CET, the `Ubuntu` bot triggered build with appending line into `./.build-trigger.txt`, but I assume that build downloaded an old version of a package. I have inspected and the pipeline has successfully finished, snap was refreshed in the repository, but old app is inside.

**Comment by Fuseteam** [comment]
that's more a regular cron job afaict otherwise it would've pulled the correct version

**Comment by Fuseteam** [comment]
wait @a-skuba how did you inspect the pipeline?

**Comment by Fuseteam** [comment]
honestly looking at the commit history it is indeed like there's a watcher in place, i wonder why it pulled the old version today

**Comment by a-skuba** [comment]
Here you have it: https://travis-ci.com/github/snapcrafters/discord

You can access it through GH Actions tab, but if you search it through a commit, you can find Travis.

Probably CDN wasn't refreshed yet on the edge of the CI server or Discord has some rolling update - my first guess.

**Comment by Fuseteam** [comment]
hmmmm the version definitely changed so i suppose cdn could be more likely

**Comment by Fuseteam** [comment]
cool ,if i'm reading this right, it looks like [github actions is capable of building snaps](https://github.com/Fuseteam/discord/runs/1502096717?check_suite_focus=true)

**Comment by Crease29** [comment]
Do you still need help with that? If yes, how can I help you? :)

**Comment by amcnea** [comment]
Don't know if this is helpful in this endeavour, but in diagnosing my discord when it was trying to force me to updated, I came across this url: https://discord.com/api/updates/stable?platform=linux&version=0.0.13

Which is what the discord app uses to check for updates during it's startup procedure.  It seems the version param isn't required in the query string either, so this works: https://discord.com/api/updates/stable?platform=linux

It returns a json payload of:
```{"name": "0.0.13", "pub_date": "2020-12-04T21:04:22"}```

**Comment by Fuseteam** [comment]
That time stamp tho, i wonder what timezone that is, it doesn't look like utc

**Comment by Fuseteam** [comment]
Base on @amcnea's findings the following command fetches just the version
`curl -s https://discord.com/api/updates/stable?platform=linux | jq .name`
I suppose this version could be compared with the version in the snap somehow, maybe hourly or something

**Comment by amcnea** [comment]
Also found these which might be useful if you wanted to implement the other release chanels:

This could be the `beta` channel:
https://discord.com/api/updates/ptb?platform=linux
`{"name": "0.0.23", "pub_date": "2020-11-24T19:37:32"}`

This could be the `edge` channel:
https://discord.com/api/updates/canary?platform=linux
`{"name": "0.0.116", "pub_date": "2020-11-24T05:33:45"}`

**Comment by Fuseteam** [comment]
`0.0.23`? oh my

**Comment by merlijn-sebrechts** [comment]
We have this now!!!

https://github.com/snapcrafters/discord/blob/candidate/.github/workflows/sync-version-with-upstream.yml

:tada:
