### ISSUE TITLE
Menu not linux mint style

### ISSUE THREAD

**Issue by Jokerling45** [snapcrafters/discord#9]
![schermafdruk op 2017-11-11 22-46-00](https://user-images.githubusercontent.com/33583628/32693852-31c3989e-c732-11e7-800f-72abd6509f9f.png)

The non-snap discord has a normal linux mint menu, but this one is different, anyway to fix it?

**Comment by simoniz0r** [comment]
I have the same issue on Xubuntu 16.04.

**Comment by oleerik** [comment]
Experiencing the same on Ubuntu 16.04.

**Comment by Fuseteam** [comment]
doesn't seem to occur on ubuntu 16.04 unity

**Comment by gluons** [comment]
Not only Discord. But seem that all apps that's installed by `snap` have the same problem.

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting everyone!!

This appears to be fixed now in the latest version of the snap, so I'm closing this issue now. Please comment if this is not the case.
