### ISSUE TITLE
Trigger rebuild for v0.0.13

### ISSUE THREAD

**Issue by a-skuba** [snapcrafters/discord#94]
Discord is prompting to update on start.  Please trigger rebuild.

**Comment by abdulb2** [comment]
Is it asking you to install the .deb? I'm having the same issue since today's update. No way to bypass this either.

**Comment by abdulb2** [comment]
> Discord is prompting to update on start. Please trigger rebuild.

Is it asking you to install the .deb? I'm having the same issue since today's update. No way to bypass this either.

**Comment by a-skuba** [comment]
Yes, seems as the build didn't fetch the latest version.

**Comment by abdulb2** [comment]
> Yes, seems as the build didn't fetch the latest version.

I see. Excuse me if this is a dumb question, but is there a reason people prefer the snap version rather than the .deb? I understand basic advantages of snap (isolation) but it seems discord has less issues if their application is manually installed from their website.

**Comment by Fuseteam** [comment]
@abdulb2 just easier, there's an option issue for resolving this issue #89

**Comment by a-skuba** [comment]
Just because it is easier and we don't have to manually download packages, since they don't have them in any repo :)

**Comment by Fuseteam** [comment]
from the looks of it the last rebuild was 15 hours ago

**Comment by a-skuba** [comment]
Yep, my mistake. Pipeline is 15hrs old.

**Comment by Fuseteam** [comment]
eh? yeah it is, if now for the update i'm not sure what triggered the pipeline

**Comment by YamiYukiSenpai** [comment]
Both edge and stable are currently at 0.0.12

**Comment by JonasRSV** [comment]
Hey I am also invested in this :) Only discord 0.0.12 is available for me and discord won't launch with 0.0.12 at the moment

**Comment by a-skuba** [comment]
Build was triggered, thanks!
https://github.com/snapcrafters/discord/pull/83#issuecomment-739154285

Closing.

**Comment by mikehardy** [comment]
Fellow open source maintainer here used to doing work and not getting thanks. Wanted to say thanks :-)
Was blocked with the 0.0.12 startup wants 0.0.13 thing but just slept on it and this morning the snap refreshed :-)
