### ISSUE TITLE
Discord slow startup time

### ISSUE THREAD

**Issue by Hans03430** [snapcrafters/discord#99]
Greetings. I have noticed that the cold startup speed for the Discord snap is quite slow. Reading through some news about the development of snaps, I ended up discovering that a new compression method was chosen in order to provide a faster startup time. but after checking the snapcraft.yaml file of Discord, I noticed LZO was not being used. My question is if there's plans to enable LZO for a faster startup time for this snap?

Thank you.

**Comment by popey** [comment]
Thanks for the report. We've switched to a different compression system (lzo) for Discord. So while not instant, it should be faster to launch now.
